# Generated by Django 5.0.3 on 2024-03-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='text_effects',
            field=models.CharField(blank=True, choices=[('bold', 'Bold'), ('italic', 'Italic'), ('underline', 'Underline')], max_length=10),
        ),
    ]
