# Generated by Django 5.0.3 on 2024-03-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_created_at_blog_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(default='', max_length=100),
        ),
    ]
